# Generated by Django 5.2.4 on 2025-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTBUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('is_super_user', models.BooleanField(blank=True, default=0, null=True)),
                ('is_user_verified', models.BooleanField(blank=True, default=0, null=True)),
                ('is_buddy', models.BooleanField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
