# Generated by Django 5.2.4 on 2025-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftbusers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
