# Generated by Django 5.2.4 on 2025-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftbusers',
            old_name='is_buddy',
            new_name='is_driver',
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='vehicle_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Bike', 'Bike')], max_length=10, null=True),
        ),
    ]
