# Generated by Django 5.2.4 on 2025-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_rename_is_buddy_ftbusers_is_driver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftbusers',
            old_name='profile_completed',
            new_name='driver_profile_completed',
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='is_rider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ftbusers',
            name='rider_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
