"""
Django settings for travel_buddy project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from configloader import confighelper
from pathlib import Path

import pymysql
pymysql.install_as_MySQLdb()


ftbtoolconfig = confighelper.getconfig()
djangoconfig = ftbtoolconfig.get("django")
smtpconfig = ftbtoolconfig.get("smtpconfig")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'userlogin.FTBUsers'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = djangoconfig.get("secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = djangoconfig.get("debug")

ALLOWED_HOSTS = [djangoconfig.get("allowedhosts")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'rest_framework.authtoken',
    'utils',
    'userlogin',
    'api_v2',
    'corsheaders',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]

#remove in prod
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'travel_buddy_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_buddy_backend.wsgi.application'


EMAIL_BACKEND = smtpconfig['backend']
EMAIL_HOST = smtpconfig['host']
EMAIL_PORT = smtpconfig['port']
EMAIL_USE_TLS = smtpconfig['use_tls']
EMAIL_HOST_USER = smtpconfig['user']
EMAIL_HOST_PASSWORD = smtpconfig['password']

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": ftbtoolconfig.get("toolmysql").get("engine"),
        "NAME": ftbtoolconfig.get("toolmysql").get("name"),
        "USER": ftbtoolconfig.get("toolmysql").get("user"),
        "PASSWORD": ftbtoolconfig.get("toolmysql").get("password"),
        "HOST": ftbtoolconfig.get("toolmysql").get("host"),
        "PORT": ftbtoolconfig.get("toolmysql").get("port"),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = djangoconfig.get("languagecode")

TIME_ZONE = djangoconfig.get("timezone")

USE_I18N = djangoconfig.get("useI18N")

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "allstatic/static")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static/"),)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ]
}

# for dev only
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" 